<?xml version='1.0'?>

<robot name="moor" xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:property name="cameraSize" value="0.05"/>
<xacro:property name="DSLRcameraSize" value="0.124"/>
<xacro:property name="cameraMass" value="0.05"/>

<xacro:macro name="default_inertia">
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
</xacro:macro>

<xacro:macro name="default_inertia_servos">
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
</xacro:macro>

<xacro:macro name="default_limit">
    <limit effort="100.0" lower="-2.62" upper="2.62" velocity="3"/>
</xacro:macro>

<xacro:macro name="default_dynamics">
      <dynamics fricction="0" damping="0" />
</xacro:macro>

  <xacro:include filename="$(find mybot_gazebo)/urdf/mybot.gazebo" />
  <xacro:include filename="$(find mybot_gazebo)/urdf/materials.xacro" />
  <xacro:include filename="$(find mybot_gazebo)/urdf/macros.xacro" />

 <!-- Base Size -->
  <xacro:property name="base_x_size" value="1" />
  <xacro:property name="base_y_size" value="0.5" />
  <xacro:property name="base_z_size" value="0.3" />

  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="0.5120" />
  <xacro:property name="track" value="0.5708" />
  <xacro:property name="wheel_vertical_offset" value="0.03282" />

  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.1" />
  <xacro:property name="wheel_radius" value="0.2" />
  <link name='base_link'>
    <pose>0 0 0.1 0 0 0</pose>

    <inertial>
      <mass value="15.0"/>
      <origin xyz="0.0 0 0.1" rpy=" 0 0 0"/>
      <inertia
         ixx="0.4233" ixy="0.0" ixz="-0.0" iyy="1.35705" iyz="-0.0" izz="1.55625"
      />
    </inertial>

    <collision name='collision'>
      <geometry>
        <box size="1 .5 .3"/>
      </geometry>
    </collision>

    <visual name='base_link_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="1 .5 .3"/>
      </geometry>
        <material name="grey"/>
    </visual>
  </link>


 

    <!-- Base footprint is on the ground under the robot -->
    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="base_footprint" />
    </joint>

    <!-- Interial link stores the robot's inertial information -->
    <link name="inertial_link">
      <inertial>
        <mass value="0.0"/>
        <origin xyz="0 0 0" />
        <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
      </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="inertial_link" />
    </joint>

  <!--link name="base_footprint">
   <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.01 0.05 0.03" />
      </geometry>

    </visual>
  </link-->

  <!--joint name="base_link_joint" type="fixed">
    <origin xyz="0.0 0 0" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint-->
  <link name="medium_left_wheel">
    <origin xyz="0 0.3 0.1" rpy="0 1.5707 1.5707"/>
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
    </collision>
    <visual name="medium_left_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
        <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="1"/>
      <cylinder_inertia m="5" r="0.2" h="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <link name="medium_right_wheel">
    <origin xyz="0 -0.3 0.1" rpy="0 1.5707 1.5707"/>
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
    </collision>
    <visual name="medium_right_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
        <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="1"/>
      <cylinder_inertia m="5" r="0.2" h="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <link name="front_left_wheel">
    <collision name="collision">
      <!--origin xyz="0 0 0" rpy="0 1.5707 1.5707"/-->
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
    </collision>
    <visual name="front_left_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
        <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="1"/>
      <cylinder_inertia m="5" r="0.2" h="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <link name="front_right_wheel">
    <collision name="collision">
      <!--origin xyz="0 0 0" rpy="0 1.5707 1.5707"/-->
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
    </collision>
    <visual name="front_right_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
        <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="1"/>
      <cylinder_inertia m="5" r="0.2" h="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

<link name="back_left_wheel">
    <!--origin xyz="0.1 0.13 0.1" rpy="0 1.5707 1.5707"/-->
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
    </collision>
    <visual name="back_left_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
        <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="1"/>
      <cylinder_inertia m="5" r="0.2" h="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>


  <link name="back_right_wheel">
    <!--origin xyz="0.1 -0.13 0.1" rpy="0 1.5707 1.5707"/-->
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
    </collision>
    <visual name="back_right_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="1"/>
      <cylinder_inertia m="5" r="0.2" h="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
</link>

  <link name="tripod_link">
    <!--origin xyz="0.1 -0.13 0.1" rpy="0 1.5707 1.5707"/-->
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="1.6"/>
      </geometry>
    </collision>
    <visual name="tripod_visual">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="1.6"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <cylinder_inertia m="5" r="0.05" h="0.5"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
</link>

 <joint type="continuous" name="medium_left_wheel_hinge">
    <origin xyz="-0.08 0.3 0" rpy="0 0 0"/>
    <child link="medium_left_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

 <joint type="continuous" name="medium_right_wheel_hinge">
    <origin xyz="-0.08 -0.3 0" rpy="0 0 0"/>
    <child link="medium_right_wheel"/>
    <parent link="base_link"/>		
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  <joint type="continuous" name="front_left_wheel_hinge">
    <origin xyz="0.34 0.3 0" rpy="0 0 0"/>
    <child link="front_left_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>
  <joint type="continuous" name="front_right_wheel_hinge">
    <origin xyz="0.34 -0.3 0" rpy="0 0 0"/>
    <child link="front_right_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>


  <joint type="continuous" name="back_left_wheel_hinge">
    <origin xyz="-0.5 0.3 0" rpy="0 0 0"/>
    <child link="back_left_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>


 <joint type="continuous" name="back_right_wheel_hinge">
    <origin xyz="-0.5 -0.3 0" rpy="0 0 0"/>
    <child link="back_right_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>
<link name="left_camera">
    <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
    </geometry>
    </collision>

    <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
    </geometry>
    <material name="grey"/>
    </visual>

    <inertial>
       <mass value="${cameraMass}" />
       <origin xyz="0 0 0" rpy="0 0 0" />
       <box_inertia m="${cameraMass}" x= "${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
       <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>
<link name="DSLR_camera_link">
    <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <!--mesh filename="/home/ali/mybot_ws/src/moor_description/meshes/DSLR.dae"/-->
      <box size="${DSLRcameraSize} ${DSLRcameraSize} ${DSLRcameraSize}"/>
    </geometry>
    </collision>
    <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <!--mesh filename="/home/ali/mybot_ws/src/moor_description/meshes/DSLR.dae"/-->
      <box size="${DSLRcameraSize} ${DSLRcameraSize} ${DSLRcameraSize}"/>
    </geometry>
    <material name="grey"/>
    </visual>

    <inertial>
       <mass value="${cameraMass}" />
       <origin xyz="0 0 0" rpy="0 0 0" />
       <box_inertia m="${cameraMass}" x= "${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
       <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>

<link name="right_camera">
    <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
    </geometry>
    </collision>

    <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
    </geometry>
    <material name="grey"/>
    </visual>

    <inertial>
       <mass value="${cameraMass}" />
       <origin xyz="0 0 0" rpy="0 0 0" />
       <box_inertia m="${cameraMass}" x= "${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
       <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>
<link name="stereocamera_baselink">
    <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="0.25 .35 0.1"/>
    </geometry>
    </collision>

    <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="0.25 0.35 0.1"/>
    </geometry>
    <material name="black"/>
    </visual>

    <inertial>
       <mass value="0.1" />
       <origin xyz="0 0 0" rpy="0 0 0" />
       <box_inertia m="0.1" x= "0.035" y="0.025" z="0.01" />
       <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>

    <link name="imu_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.02 0.02"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.02 0.02"/>
            </geometry>
            <material name="red"/>
        </visual>
        <inertial>
            <mass value="0.001" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.00000015" ixy="0" ixz="0" iyy="0.00000015" iyz="0" izz="0.00000015" />
        </inertial>
</link>

<joint name="imu_joint" type="fixed">
  <axis xyz="0 1 0" />
  <origin xyz="0 0 0" rpy="0 0 0"/>
  <parent link="stereocamera_baselink"/>
  <child link="imu_link"/>
</joint>

<joint name="stereocamera_baselink_joint" type="fixed">
  <axis xyz="0 1 0" />
  <origin xyz="0.28 0 0.2" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="stereocamera_baselink"/>
</joint>

<joint name="tripod_joint" type="fixed">
  <axis xyz="0 1 0" />
  <origin xyz="-0.45 0 0.8" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="tripod_link"/>
</joint>

<joint name="DSLR_camera_joint" type="fixed">
  <axis xyz="0 1 0" />
  <origin xyz="0 0 0.8" rpy="0 0 1.5707"/>
  <parent link="tripod_link"/>
  <child link="DSLR_camera_link"/>
</joint>

<joint name="left_camera_joint" type="fixed">
  <axis xyz="0 1 0" />
  <origin xyz="0.1 0.15 0" rpy="0 0 0"/>
  <parent link="stereocamera_baselink"/>
  <child link="left_camera"/>
</joint>

<joint name="right_camera_joint" type="fixed">
  <axis xyz="0 1 0" />
  <origin xyz="0.1 -0.15 0" rpy="0 0 0"/>
  <parent link="stereocamera_baselink"/>
  <child link="right_camera"/>
</joint>

  <joint name="base_laser_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz=".45 0 0.26" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="base_laser"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="base_laser">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <!--mesh filename="/home/ali/mybot_ws/src/moor_description/meshes/hokuyo.dae"/-->
        <box size="0.05 0.05 0.05"/>
      </geometry>
     <material name="red"/>
    </collision>

    <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <!--mesh filename="/home/ali/mybot_ws/src/moor_description/meshes/hokuyo.dae"/-->
        <box size="0.05 0.05 0.05"/>
      </geometry>
    <material name="red"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>


<link name="mainboard">
    <collision>
    <origin xyz="0 -0.4 0" rpy="0 0 0"/>
    <geometry>
      <box size="0.25 .35 0.1"/>
    </geometry>
    </collision>

    <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="0.25 0.35 0.1"/>
    </geometry>
    <material name="red"/>
    </visual>

    <inertial>
       <mass value="6" />
       <origin xyz="0 0 0" rpy="0 0 0" />
        <box_inertia m="6" x= "0.25" y="0.35" z="0.1" />
       <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>

<joint name="mainboard_joint" type="fixed">
  <axis xyz="0 1 0" />
  <origin xyz="-0.38 0 0" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="mainboard"/>
</joint>
</robot>
